//all users
const LOAD_PRODUCTS = "LOAD_PRODUCTS";
const LOAD_PRODUCT = "LOAD_PRODUCT";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";

//Admin
const CREATE_PRODUCT = "CREATE_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";


export {LOAD_PRODUCTS, LOAD_PRODUCT, FILTER_PRODUCTS, CREATE_PRODUCT, DELETE_PRODUCT, EDIT_PRODUCT}