// All users
const LOAD_REGION = "LOAD_REGION";
const LOAD_REGIONS = "LOAD_REGIONS";

//Admin 
const CREATE_REGION = "CREATE_REGION";
const EDIT_REGION = "EDIT_REGION";
const DELETE_REGION = "DELETE_REGION";

export {LOAD_REGION, LOAD_REGIONS, CREATE_REGION, DELETE_REGION, EDIT_REGION}