// All users
const LOAD_CATEGORIES = "LOAD_CATEGORIES";
const LOAD_CATEGORY = "LOAD_CATEGORY";

// Admin
const CREATE_CATEGORY = "CREATE_CATEGORY";
const EDIT_CATEGORY = "EDIT_CATEGORY";
const DELETE_CATEGORY = "DELETE_CATEGORY";

export {LOAD_CATEGORIES, LOAD_CATEGORY, CREATE_CATEGORY, EDIT_CATEGORY, DELETE_CATEGORY}